### ISSUE TITLE
Add Rubocop to the test suite

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#119]
It's annoying having the hound comment and generates a lot of noise. The error correction is most useful before you commit, not after.

**Comment by ramillim** [comment]
I've seen developers use the Overcommit gem before: https://github.com/brigade/overcommit
It doesn't run on test, but rather on git commit, so you could configure the repository to run your Rubocop linter and several other git pre-commit hooks if desired.

Might be worth taking a look at.

**Comment by williamcodes** [comment]
This looks awesome! All the fun of pre-commit hooks with none of the
miserable configuration. I'll open an issue for it.
