### ISSUE TITLE
Form style updates

### ISSUE THREAD

**Issue by ramillim** [heatseeknyc/heatseeknyc#123]
Make the Sign In and New User registration form consistently use the same style as the Settings Form instead of generic bootstrap.

In the User edit page, make the following tweaks:
Part 1
1. move sensor code above password
2. create a separation between password and password confirmation and current password
3. increase size of the "tooltip" fonts next to the input fields

Part 2
4. create a separate form for changing password
5. make deleting the account require a password

Part 3
6. update css in user sign in form, password reset, and password edit (from password reset) forms

**Comment by williamcodes** [comment]
closed by #143
