### ISSUE TITLE
create a swag store

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#139]
We keep getting requests for more Heat Seek swag like t-shirts and hoodies. Let's integrate with Shopify, Printfection, WooCommerce, whoever. The main challenge is finding someone who will handle sourcing, shipping, and billing so we can just provide the designs up-front and leave it running. We're not a t-shirt company, let's not get bogged down in retail.

**Comment by cromulus** [comment]
I've got a bunch of solutions to this. Let's talk.
