### ISSUE TITLE
building model

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#152]
Create a building model and replace the address attribute on the user class with a relationship to a building. We'll have to run some kind of script to update all the users in the database. We should be careful to maintain backwards compatibility here.

**Comment by ramillim** [comment]
It may be worth creating a Blocker label to tag stories such as this one that other work is dependent on.  I just referenced this in the CSV export story.

**Comment by ramillim** [comment]
While working on this, I started thinking that the Apartment model and Building has many Tenants through Apartments relationship made the most logical sense, but overcomplicated things for the time being until we decide we want to tackle that refactor (and migrating all the data from the users table).

The biggest smell for this was that apartment is just an attribute on the User model while User now has a direct association to the Building and Building must go through User to get through Apartment.

Whenever we decide to add Apartments, I think we will also want to add the apartment_id to the Reading so a Reading is associated with both a User (tenant) and an Apartment.
