### ISSUE TITLE
Create building view page with building summary info

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#163]
Building summary info includes address, BBL, BIN, landlord, census block, management company. Any other info associated with the model should be considered if available.

**Comment by ramillim** [comment]
I have only implemented the /admin/buildings/edit in the current PR.

I am thinking there would be a separate read-only /buildings/:id show that advocates would be able to access that displays this. Alternatively, it could remain in the /admin namespace also.

**Comment by williamcodes** [comment]
I like the idea of building show pages. My vote is for /buildings as a namespace, it's more RESTful. I could see an argument for /admin though.

**Comment by ramillim** [comment]
I think that the root/buildings/ could display something like the map with the buildings at http://heatseek.org/pilot/ or it could be a JSON endpoint to serve dynamic maps like that.

Then root/admin/buildings/ could be more for content management with features like searching for buildings, editing existing, creating new ones.
