### ISSUE TITLE
Store Building geo-coordinates on model

### ISSUE THREAD

**Issue by ramillim** [heatseeknyc/heatseeknyc#185]
Since we have a building model now, it may be useful to store the lat/long on the Building model. This can be backfilled with the coords currently used for the CartoDB map.  For future buildings added, we could write up something to automatically make a geocoding request through the GoogleMaps API or something similar.

**Comment by jhack32** [comment]
Added longitude/latitude to Buildings table. Also added Buildings model.

https://github.com/heatseeknyc/heatseeknyc/pull/197
