### ISSUE TITLE
Update tenant list for new design

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#198]
We have new mockups for the tenant page that HPD and advocacy groups see. It provides better summary data and controls.
- organization-wide view
  - see all tenants grouped by building
  - see summary info without having to click on individual tenants
  - if they're currently in violation
  - how many violations that week
- filtering & sorting
  - only violations that are more than 2ºF below the limit
  - see buildings with the most violations
  - see buildings with multiple tenants on multiple floors with no heat 

[20160711_heatseek_mockup (1).pdf](https://github.com/heatseeknyc/heatseeknyc/files/382718/20160711_heatseek_mockup.1.pdf)

**Comment by ramillim** [comment]
👍 
I'm currently traveling, but hope to PR the updates to the tenant forms for setting buildings and apartments next week so that the data will be there to serve these new views.
