### ISSUE TITLE
create a logger for quality control

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#31]
Currently the QualityControl class uses `puts` to do logging. Upgrade this to a proper logger so you can get feedback while using the tool but it doesn't show up when running the test suite.

**Comment by williamcodes** [comment]
I would call this a 3 point story but I've never made a logger before. Shouldn't be hard? Probably?

**Comment by oliverbarnes** [comment]
Are you making a logger from scratch or just injecting the rails (or
another existing) logger into it?

**Comment by williamcodes** [comment]
Good question. I'm actually not familiar with the rails logger. Given that Rails already has a logger, I would say we should probably just use that. We need it to log to the console when using `rails console` but not log to STDOUT when running the test suite. Can the Rails logger do that?

**Comment by oliverbarnes** [comment]
It outputs to a `log/(test|development|production).log` file and to STDOUT as the server output (`rails s`). Under rspec it outputs only to the `test.log` file.

On the console, you'll still need `puts` to see anything.

You can always leave a terminal open tailing the log to see it in real time, no matter which environment you're in:

```
$ tail -f log/development.log
$ tail -f log/development.log
```

**Comment by williamcodes** [comment]
Hmm, perhaps the best solution then is to pass an optional parameter that suppresses the `puts` during testing instead of messing with loggers then. The idea here is to provide some console tools in case we need to do some quality control on the data. That's why the feedback in the console is important. This issue got created when someone noticed that the QualityControl class was filling the test suite up with noise from the all the `puts` statements.

**Comment by oliverbarnes** [comment]
sure, you could have a `debug` option and a conditional checking for it. Or you could just have a check for `Rails.env.test?`.

I'm not familiar with the purpose of the `QualityControl` class (the tests don't seem have much info about it), so I wouldn't know if having a historical log to be checked afterwards would be useful.

**Comment by williamcodes** [comment]
Using `Rails.env.test?` would work, but making the method return different results depending on the environment could create surprises.

The idea of the QualityControl class is to allow us to update the outdoor temperatures for readings that are missing that information, as well as to remove duplicate readings. Because of that, I think historical logs to be checked afterwards would be nice to have but not necessary.

**Comment by williamcodes** [comment]
I put in an optional parameter to make it silent, which is working well, so I'm closing this issue.
