### ISSUE TITLE
integrate live-update CartoDB visualization

### ISSUE THREAD

**Issue by namessanti** [heatseeknyc/heatseeknyc#35]
As a government agency,
When I log in,
Then I see which buildings are in violation in real time

Acceptance Criteria:
- write a SQL query to join user and reading data (anonymized)
- rename timestamp criteria for use in CartoDB (can not be 'created_at')
- Latitude and Longitude columns in place of addresses (I can do this and send it back)

Thats it! : )

**Comment by namessanti** [comment]
http://bl.ocks.org/namessanti/raw/58066e3ec95991e679fd/    <- Viz

http://bl.ocks.org/namessanti/58066e3ec95991e679fd/   <- Code

**Comment by oliverbarnes** [comment]
@williamcodes want to pair on this? or any of the other issues, whatever is highest priority

**Comment by williamcodes** [comment]
@essejhsif would you be able to write a SQL query for @namessanti's visualization? It needs to join user and reading data, omit columns with personal information, and rename timestamp column from `created_at` to `reading_taken`. Once we have a query we can set up an endpoint and work on converting addresses to coordinates.
