### ISSUE TITLE
get action mailer to allow devise password reset emails through

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#36]
As a user,
When I forget my password,
Then I receive an email with the password reset link

Notes:
It looks like action mailer is not configured yet. Doing that would probably make it work.

**Comment by williamcodes** [comment]
@oliverbarnes this would be a great one to pair on. When are you free?

**Comment by oliverbarnes** [comment]
Hey, how about tomorrow 12:30 PM EST?

**Comment by williamcodes** [comment]
@oliverbarnes I've got a meeting then. Can you do 4pm?

**Comment by williamcodes** [comment]
@oliverbarnes unless you have an idea of how to fix the problem and think it will be easy to fix. I've got meetings from 10am - 12:30pm and 1:30pm - 3:30pm.

**Comment by oliverbarnes** [comment]
yeah, might not be worth pairing on. it does sound like you just need to configure action mailer. what are you guys planning on using for email? Sendgrid?

**Comment by williamcodes** [comment]
Okay, we can pick a different issue. I can do 12:30pm now that I've cancelled my meeting at 10am. Can you do earlier? That way we'll have more time.
