### ISSUE TITLE
Test coverage for twine scraper

### ISSUE THREAD

**Issue by oliverbarnes** [heatseeknyc/heatseeknyc#5]
Hello Heatseekers,

I listened to @williamcodes on rubyrogues, and was really impressed by the project. I'd love to contribute to the codebase if I can.

Thought of helping with test coverage and some refactorings first, and have been looking at the twine scraper as a place to start. I'm wondering if it'd be possible to use vcr to record an interaction with the twine.cc site? 

I haven't found any mention of a sandbox account when googling their service. Is there such an account? If not, is it worth asking them for one?

**Comment by williamcodes** [comment]
Killer job Oliver! I was gone for the holidays and just had a chance to
review all your pull requests. Insufficient code coverage has been a huge
issue for us. We took on technical debt by pushing out features without
tests and after a while it got harder to feel confident about pushing new
code. These new tests you've added make me feel a lot more confident that
the site will keep running smoothly for people when we deploy new features,
so thank you. The reorganization was also helpful, you've got a great eye
for architecture. After having spent some time in the codebase, what are
your thoughts? Any areas in particular that you think could use the most
refactoring? I've got some thoughts too but I'm curious about your opinion.

**Comment by oliverbarnes** [comment]
Thanks! Glad it's all been helpful. I love architecture and refactoring, so it's great to hear this :) 

I'm traveling now myself (a beach in Alagoas, not bad at all), finally sat down to respond too.

I think the codebase is in pretty good shape. I get it that some technical debt was taken to ship quickly, with limited resources I'm guessing, but I see care in keeping things tidy enough that it could be picked up later without too much trouble. Good sane pragmatism. 

I'd probably refactor concerns next? I see possible services, decorators and/or value objects there. What's your take?

And continue adding coverage, starting with more [acceptance specs](https://github.com/heatseeknyc/heatseeknyc/issues/6)

**Comment by williamcodes** [comment]
Anywhere near Maceio? Beautiful beaches out there. I have a few friends out
there, did you check out the natural pools? I remember they came around
with floating trays of seafood, I wish I had more vacations like that!

Glad to hear you think the code base is in pretty good shape. I think
you're spot on with refactoring concerns next. I once read that any
application with a big app/concerns directory is concerning. I think
there's truth to that, it turns into a junk drawer. I'm not sure what the
best way to tackle it is, but services, decorators, and/or value objects
all seem like good patterns. I'd love to see your take on it.

Also for test coverage, I agree, having some capybara features in there to
test end-to-end would also be great. If you write any, I'd love to hook
them up to our continuous deployment system so they run every time we push
code.

**Comment by oliverbarnes** [comment]
Yeah, in Tatuamunha, a couple of hours north of Maceió.  [Tropical Ruby](http://tropicalrb.com) will happen not far from there in March. I ended up not checking the natural pools, but the beaches there are pretty amazing already. There's a massive coral-reef pretty much spanning Alagoas state, so when the tide lowers you can walk several hundred meters into the sea... Recommended.

Cool, I'll get started with the concerns then. About the feature specs, it'd be useful to discuss what the main user stories are on [this issue](https://github.com/heatseeknyc/heatseeknyc/issues/6)

About the CI, I clicked on the codeship badge but the build doesn't show up for some reason, though the url seems right

**Comment by williamcodes** [comment]
Speaking of Tropical Ruby, I just heard on Ruby Rogues that Avdi Grimm is
going to be a speaker there. Are you going? I'm jealous, Tatamunha sounds
awesome and, oh man, I miss the weather.

By the way, I added you to the team on Codeship, so perhaps that link will
work now.

As for the user stories, what do you think of this:

- Admin manages users/twines/sensors/...
As an admin
When I log in
And I go to the sensors page
Then I see the sensors my organization owns
When I assign a sensor to a tenant
Then I see the sensor assigned to that tenant

- Tenant downloads report
As a tenant
When I log in
Then I see my readings graph
When I download my report
Then I get a PDF of my readings


- Admin / lawyer views complaints
As a lawyer
When I log in
And I go to the tenants page
Then I see the tenants in my organization

Visitor views coldmap
As a visitor
When I visit the coldmap page
Then I see the coldmap

**Comment by oliverbarnes** [comment]
Yup, I'm going :) Get your boss to send you there! You could give a talk about Heatseek too, people would really dig it.

Thanks for the user stories, that's a good start. I'm reposting them on the specific issue just to keep communication easy to track
