### ISSUE TITLE
Add LandlordLookup frontend to site

### ISSUE THREAD

**Issue by kronosapiens** [heatseeknyc/heatseeknyc#50]
Issue is to host the LandlordLookup frontend (https://github.com/jbouzi12/LandlordLookup) on the Heat Seek site.

The frontend is set up to make requests to https://hpd-elephantbird.rhcloud.com/ and display the results.

The issue can be as simple as copying the code into this repo and re-deploying. We are not hosting the data ourselves, so we fortunately don't have to worry about the backend support for this feature just yet.

Related to #51 (navigation)

**Comment by williamcodes** [comment]
Done, this is linked to at lookup.heatseek.org
