### ISSUE TITLE
return 200 OK if perfect dupe exists and ignore

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#90]
There's no sense in throwing 400s for dupes. We can just ignore them. @hrldcpr is it helpful for you to know when there are dupes? I feel like the relay wouldn't care any more than the app server does. Unless that's useful info for debugging and the relay has logic to give up on dupes.

**Comment by hrldcpr** [comment]
Yeah that would be fine. :sunflower:

**Comment by williamcodes** [comment]
closed by #95
