### ISSUE TITLE
Fix Travis CI or rip it out

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#92]

**Comment by oliverbarnes** [comment]
Digging. Why is database.yml encryption needed?

**Comment by oliverbarnes** [comment]
Looks like the secure variables needed for the encryption script aren't available because PR #99 is coming from a fork :/

> A pull request sent from a fork of the upstream repository could be manipulated to expose any environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone with a fork.

> For the protection of secure data, Travis CI makes it available only on pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

> Pull requests sent from forked repositories don’t have this data available in their builds. All data that’s considered confidential will not be added to the build’s environment.

https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

**Comment by oliverbarnes** [comment]
> To work around this, you could restrict these tests only to situations where the environment variables are available, or disable them for pull requests entirely. Here’s an example of how to structure a build command for this purpose:

```
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake tests:integration || false'
```

> The environment variable ${TRAVIS_PULL_REQUEST} is set to "false" when the build is for a normal branch commit. When the build is for a pull request, it will contain the pull request’s number.

That would mean different builds for external PRs, though. Not sure that's desirable

**Comment by williamcodes** [comment]
The database.yml file is encrypted because it can't be under version control if we want it to be different in production and local. We need it to be different because our database.yml includes a secure password for the database. Perhaps we could use an environment variable with erb. I think there used to be an issue with the database.yml loading before loading figaro environment variables in rails 3, but I think it's been resolved. If we use that approach we could still run travis on external PRs.

**Comment by williamcodes** [comment]
Just looking into whether we can use Codeship exclusively or if we need to keep Travis CI and it looks like Codeship doesn't run on external PRs:

https://codeship.com/documentation/faq/testing-prs-from-forked-repositories/

Based on that, we should probably keep Travis CI and just fix this database problem.

**Comment by oliverbarnes** [comment]
Want to hop on screenhero tomorrow at some point to fix this? I don't know enough of the deployment strategy to submit a PR for this on my own

**Comment by williamcodes** [comment]
That sounds awesome. How about 12pm EST / 3pm BRST?

**Comment by oliverbarnes** [comment]
oops, busy couple of days and ended up not checking back. Today at some point?

**Comment by williamcodes** [comment]
Been totally slammed, you free Friday before 12pm EST / 3pm BRST?

**Comment by oliverbarnes** [comment]
Só no desencontro :) uma hora a gente consegue

**Comment by williamcodes** [comment]
I think this is fixed thanks to @ramillim, closing it for now.
