### ISSUE TITLE
Make download of PDF faster

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/heatseeknyc#96]
Right now for users with more than a month of readings, downloading a PDF can take upwards of 10 seconds. This leads users to think the site is broken, or to hit the download button many times. This story is to make the downloads fast again.

As a tenant,
When I download my heat log,
And I am on a good internet connection,
Then I should wait < 1000ms for the file to download

Notes:
I checked to see if we were making an N+1 query, and while the code is very poorly factored, it only hits the database once. The database call and iterating through the results to created a nested array takes about 750ms, which isn't snappy but definitely does not explain the download time.

After doing some further research, it appears that this problem was common in older versions of Prawn. It seems they have since moved to v2.x, and we are still on v1.0, so upgrading may fix the problem. However, given that we have explicitly set the version to v1.0, I would wager that substantial changes have been made to the gem and upgrading will be nontrivial.

**Comment by ramillim** [comment]
Did a quick look at how the users are downloading the PDFs. I think one option to give the user feedback is to switch the button action to an ajax request. User clicks on it, the text changes to "Preparing PDF" or something similar, and then once the PDF has been generated, button changes to "Click to Download" or I think you would probably just be able to complete the get request and open up the browser's download dialogue.

In the long term, as the available data gets larger and the user base grows, it will become necessary to add worker nodes that pull the jobs to generate a pdf off of a queue. Resque is a queue implementation for Rails that I've used before.  You would be able to check if there is already a job on the queue to generate the PDF in case the user clicks multiple times and tries to queue up multiple jobs. It won't be possible if you lock to only one job at a time per user id.

**Comment by ramillim** [comment]
Another option would be to cache the results of the nested array generation on the User model or a separate table and have it be a nightly job and only generate PDF for data from the complete previous day.  Using a JSONB column is viable if your version of postgres is new enough and something I've used before to cache data.  HSTORE would probably work too, but I'm not a fan of HSTORE.

**Comment by williamcodes** [comment]
Good point about needing Resque eventually, I hadn't thought of that but you're right. Also, the AJAX option is probably the right answer, I've looked into it and it seems like PDF generation is just inherently a slow process, so I don't know what else we can do performance-wise. As for caching or doing nightly jobs, I suspect users will dislike that. We had a 6 hour delay on the logs and got emails from users asking about the missing data.
